-- Kategorý tablosu oluþturma
CREATE TABLE CATEGORY (
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
CATEGORY_NAME VARCHAR(50) )


--Kategoriye tablosuna veri girme 

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Bilgisayar')
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Teknik Servis')
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Giyilebilir Teknoloji')



--Para birimi tablosu oluþturma
CREATE TABLE CURRENCY(
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
KOD CHAR(3),
CURRENCY_NAME VARCHAR(30))

--Para birimi tablosuna veri girme 

INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('USD','Amerika Birleþik Devletleri')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('EUR' ,'Avrupa Birliði')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('GBP','Birleþik Krallýk')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('JPY','Japonya')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('CNY','Çin')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('CAD' ,'Kanada')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('AUD','Avustralya')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('CHF' ,'Ýsviçre')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('INR','Hindistan')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('RUB' ,'Rusya')
INSERT INTO CURRENCY (KOD,CURRENCY_NAME) VALUES ('TL','Türkiye')




-- Ürün tablosu oluþturma

CREATE TABLE PRODUCT (
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
CATEGORYLOGREF INT FOREIGN KEY REFERENCES CATEGORY(LOGREF) NOT NULL,
PRODUCT VARCHAR(60) NOT NULL,
BRAND VARCHAR(30) ,
PRICE DECIMAL(10,2) NOT NULL,
CURRENCYLOGREF INT FOREIGN KEY REFERENCES CURRENCY(LOGREF) NOT NULL)


--Ürün tablosuna veri girme

INSERT INTO PRODUCT(CATEGORYLOGREF,PRODUCT,BRAND,PRICE,CURRENCYLOGREF) VALUES ('1','LEPTOP','LENOVO','15000','11')
INSERT INTO PRODUCT(CATEGORYLOGREF,PRODUCT,BRAND,PRICE,CURRENCYLOGREF) VALUES ('1','TABLET','SAMSUNG','250','2')
INSERT INTO PRODUCT(CATEGORYLOGREF,PRODUCT,BRAND,PRICE,CURRENCYLOGREF) VALUES ('3','AKILLI SAAT','XIAMO','120','5')
INSERT INTO PRODUCT(CATEGORYLOGREF,PRODUCT,BRAND,PRICE,CURRENCYLOGREF) VALUES ('2','FORMAT',NULL,'500','11')
