--Firma tablosu oluþturma
/*
CREATE TABLE COMPANY (
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
COMPANY_NAME VARCHAR(20) NOT NULL,
BRANCH VARCHAR(15)
)
*/

-- Firma tablosuna veri girme 
/*
INSERT INTO COMPANY (COMPANY_NAME,BRANCH) VALUES ('Kalde','Ankara')
INSERT INTO COMPANY (COMPANY_NAME,BRANCH) VALUES ('Filyos Yapý','Zonguldak')
INSERT INTO COMPANY (COMPANY_NAME,BRANCH) VALUES ('Tp-link','Ýstanbul')
INSERT INTO COMPANY (COMPANY_NAME,BRANCH) VALUES ('Mojue','Bartýn')
INSERT INTO COMPANY (COMPANY_NAME,BRANCH) VALUES ('Bugatek','Karabük')
*/