--Müsteri tablosu oluþturma

CREATE TABLE CUSTOMER(
LOGREF INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
TC CHAR(11)  NOT NULL,
GENDER CHAR(1),
FIRST_NAME VARCHAR(30) NOT NULL,
SURNAME VARCHAR(30) NOT NULL,
PHONE_NUMBER CHAR(10) NOT NULL,
WORK_PHONE CHAR(12),
MAIL VARCHAR(25),
DATE_OF_BIRTH DATE,
ADRESSLOGREF INT FOREIGN KEY REFERENCES ADRESS(LOGREF) NOT NULL,
COMPANYLOGIREF INT FOREIGN KEY REFERENCES COMPANY(LOGREF) NOT NULL,
PRODUCTLOGREF INT FOREIGN KEY REFERENCES PRODUCT(LOGREF) NOT NULL,
DEBT DECIMAL(10,2) NOT NULL,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
EXPLANATION VARCHAR(200),
CREATE_DATE DATE,)


--Müþteri tablosuna veri girme 

INSERT INTO CUSTOMER(TC,GENDER,FIRST_NAME,SURNAME,PHONE_NUMBER,WORK_PHONE,MAIL,DATE_OF_BIRTH,ADRESSLOGREF,COMPANYLOGIREF,PRODUCTLOGREF,DEBT,EMPLOYEE_NAME,EXPLANATION,CREATE_DATE) VALUES ('111','E','Ahmet','Türk','200','2000','a.a@a','1985.02.17','1','4','1','30000','aÇalýþan','2 adet leptop satýldý','2024.09.23')
INSERT INTO CUSTOMER(TC,GENDER,FIRST_NAME,SURNAME,PHONE_NUMBER,WORK_PHONE,MAIL,DATE_OF_BIRTH,ADRESSLOGREF,COMPANYLOGIREF,PRODUCTLOGREF,DEBT,EMPLOYEE_NAME,EXPLANATION,CREATE_DATE) VALUES ('444','K','Melek','Yýlmaz','300','3000','b.b@b','2000.05.12','2','1','2','1000','bÇalýþan','4 adet tablet satýldý','2024.09.22')
INSERT INTO CUSTOMER(TC,GENDER,FIRST_NAME,SURNAME,PHONE_NUMBER,WORK_PHONE,MAIL,DATE_OF_BIRTH,ADRESSLOGREF,COMPANYLOGIREF,PRODUCTLOGREF,DEBT,EMPLOYEE_NAME,EXPLANATION,CREATE_DATE) VALUES ('777','K','Menekþe','Alagöz','500','5000','c.c@c','1990.06.11','3','2','4','500','cÇalýþan','bilgisayarýna format atýldý','2024.09.21')
