
--MÜÞTERÝ TABLOSUNDAN AD SOYAD VE ADRES TABLOSUNDAN KALDIKLARI ÞEHÝR VE AÇIK ADRESLERÝNÝ GETÝR

SELECT FIRST_NAME,SURNAME ,CITY,OPEN_ADDRESS 
FROM CUSTOMER FULL JOIN ADRESS ON CUSTOMER.ADRESSLOGREF=ADRESS.LOGREF


--MÜÞETÝLERÝN ÖDEDÝÐÝ TUTARLARI GETÝR

SELECT FIRST_NAME,SURNAME, DEBT_PAID 
FROM DEBTS FULL JOIN CUSTOMER ON DEBTS.CUSTOMERLOGREF=CUSTOMER.LOGREF




